---
title: "TidyTuesday.7.6.20"
author: "Sophia Foster"
date: "7/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(ggplot2)
library(sf)
library(patchwork)

theme_set(
  theme_classic()
  )
```

```{r}
tuesdata <- tidytuesdayR::tt_load('2020-07-07')
tuesdata <- tidytuesdayR::tt_load(2020, week = 28)

coffee_ratings <- tuesdata$coffee_ratings
```

```{r}
ratings_tidy <- coffee_ratings %>%
  select(country_of_origin, total_cup_points) %>%
  group_by(country_of_origin) %>%
  summarize(average_rating = mean(total_cup_points)) %>%
  drop_na(country_of_origin) %>%
  mutate(region = country_of_origin)

View(ratings_tidy)
```

```{r}
countries <- map_data("world")

countries_tidy <- countries %>% 
  select(region) %>%
  distinct(region)
  
    
View(countries_tidy)
```

```{r}
full_joined <- left_join(countries_tidy, ratings_tidy, by = "region")

full_joined <- full_joined %>% 
  select(-country_of_origin) 

view(full_joined)
```

```{r}
world_map <- map_data("world")
rating.map <- left_join(full_joined, world_map, by = "region")
```

```{r}
map <- ggplot(rating.map, aes(map_id = region, fill = average_rating))+
  geom_map(map = rating.map,  color = "white")+
  expand_limits(x = rating.map$long, y = rating.map$lat)+
  scale_fill_gradient( low = "wheat", high = "sienna4",
  #space = "Lab",
  na.value = "grey50") +
  theme_void()+
  labs(title ="Title", subtitle = "Average cup points by county", fill="Series") +
  theme(plot.title = element_text(hjust = 0.5, size = 25, color="Purple")) +
  theme(plot.subtitle = element_text(hjust = 0.5, face = "italic", color="violet", size = 15))

map
```

```{r}
best_rated <- ratings_tidy %>%
  arrange(desc(average_rating)) %>%
  slice(1:10)

best_rated
```

```{r}
bar <- ggplot(best_rated, aes(x= reorder(region, average_rating), y=average_rating), fill= "Brown") +
  geom_col() +
  coord_flip(ylim=c(82, 86)) +
  theme_minimal() +
  labs(title ="Top Countries", subtitle = "Average cup points by county", fill="Series") +
  theme(plot.title = element_text(hjust = 0.5, size = 25, color="DarkGreen")) +
  theme(plot.subtitle = element_text(hjust = 0.5, face = "italic", color="Green", size = 15))+
  theme(plot.background = element_rect(fill = "blanchedalmond"))


bar
```

```{r}
layout <- '
AAAB
AAAB
'
map + bar + plot_layout(design = layout)

#map/ (bar + bar)

```

