---
title: "7-14-20"
author: "Sophia Foster"
date: "7/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(ggplot2)
library(sf)
library(patchwork)
```

```{r}
tuesdata <- tidytuesdayR::tt_load('2020-07-14')
tuesdata <- tidytuesdayR::tt_load(2020, week = 29)

astronauts <- tuesdata$astronauts
```

```{r}
countries_most <- astronauts %>%
  group_by(nationality) %>%
  summarise(n= n_distinct(name))%>%
  arrange(desc(n)) %>%
  slice(1:2)

top_countries <- countries_most$nationality

astronauts_tidy <- astronauts%>%
  mutate(age_of_selection = year_of_selection - year_of_birth) %>%
  distinct(name, .keep_all = TRUE)%>%
 # recode(nationality != "U.S." && nationality!="U.S.S.R/Russia", "Other")
#%>%
 filter(nationality %in% top_countries)

#%>%
 # recode(top_countries, "other")
```

```{r}
colors <- c("gold", "deepskyblue")

ggplot(astronauts_tidy, aes(x=year_of_selection, y=age_of_selection, color = sex))+
  geom_point()+
  facet_wrap(~nationality)+
  scale_color_manual(values = colors)+
  theme_minimal()+
  labs(title ="Who Goes to Space?", subtitle = "Age and gender over time for astronauts from the leading countries in space", Color="Sex", x="Year of Selection", y="Age of Selection")+
  theme(plot.subtitle = element_text(hjust = 0.5, face = "italic", color="white", size = 15))+
  theme(plot.title = element_text(hjust = 0.5, size = 25, color="white"))+
  theme(plot.background = element_rect(fill = "black"))+
  theme(legend.title = element_text(color = "white"),
  legend.text = element_text(color = "white"))+
  theme(axis.title.x = element_text(colour = "white"),
        axis.title.y = element_text(colour = "white"))+
  theme(axis.text = element_text(colour = "white"))

#limit to only the most common nationalitie with others recoded as "other"
```

